name: iOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: 11

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7.4'

    - name: Install CocoaPods
      run: sudo gem install cocoapods -v 1.15.0

    - name: Install dependencies
      run: pod install --repo-update
      working-directory: .

    - name: Fix script permissions
      run: chmod +x Pods/Target\ Support\ Files/Pods-OfflineGPSTracker_Xcode/Pods-OfflineGPSTracker_Xcode-frameworks.sh

    - name: Build the app
      run: |
        xcodebuild -workspace OfflineGPSTracker_iOS/OfflineGPSTracker_Xcode.xcworkspace \
                   -scheme OfflineGPSTracker_Xcode \
                   -sdk iphonesimulator \
                   -configuration Debug \
                   build \
                   -destination 'platform=iOS Simulator,name=iPhone 11,OS=12.1' \
                   CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO \
                   DEVELOPMENT_TEAM=WH83B583SU
      working-directory: .

    - name: Archive the app
      run: |
        xcodebuild -workspace OfflineGPSTracker_iOS/OfflineGPSTracker_Xcode.xcworkspace \
                   -scheme OfflineGPSTracker_Xcode \
                   -sdk iphonesimulator \
                   -configuration Release \
                   archive \
                   -archivePath $PWD/OfflineGPSTracker_iOS/build/OfflineGPSTracker_Xcode.xcarchive \
                   CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO \
                   DEVELOPMENT_TEAM=WH83B583SU
      working-directory: .

    - name: Validate archive
      run: |
        if [ ! -d $PWD/OfflineGPSTracker_iOS/build/OfflineGPSTracker_Xcode.xcarchive ]; then
          echo "Archive not found or not created correctly!"
          exit 1
        else
          echo "Archive found and created correctly."
          ls -la $PWD/OfflineGPSTracker_iOS/build/
        fi
      working-directory: .

    - name: Export IPA
      run: |
        xcodebuild -exportArchive \
                   -archivePath $PWD/OfflineGPSTracker_iOS/build/OfflineGPSTracker_Xcode.xcarchive \
                   -exportOptionsPlist $PWD/OfflineGPSTracker_iOS/ExportOptions.plist \
                   -exportPath $PWD/OfflineGPSTracker_iOS/build/OfflineGPSTracker_Xcode \
                   CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO \
                   DEVELOPMENT_TEAM=WH83B583SU \
                   | tee export.log
      working-directory: .

    - name: Find and copy export logs
      run: |
        LOG_DIR=$(ls -td /var/folders/*/*/*/OfflineGPSTracker_Xcode_*.xcdistributionlogs | head -1)
        echo "Log directory: $LOG_DIR"
        if [ -d "$LOG_DIR" ]; then
          mkdir -p $GITHUB_WORKSPACE/xcdistributionlogs
          cp -R "$LOG_DIR"/* $GITHUB_WORKSPACE/xcdistributionlogs/
          echo "Logs copied successfully."
        else
          echo "Log directory not found."
          exit 1
        fi

    - name: Upload export logs
      uses: actions/upload-artifact@v3
      with:
        name: xcdistributionlogs
        path: xcdistributionlogs

    - name: Upload build log
      uses: actions/upload-artifact@v3
      with:
        name: export-log
        path: export.log

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: OfflineGPSTracker_Xcode
        path: $PWD/OfflineGPSTracker_iOS/build/OfflineGPSTracker_Xcode
