name: iOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: 11

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7.4'  # Specify Ruby 2.7.4 or later

    - name: Install CocoaPods
      run: sudo gem install cocoapods -v 1.15.0

    - name: Install dependencies
      run: pod install --repo-update
      working-directory: .  # Adjust if your project is in a subdirectory

    - name: Set up Xcode
      run: sudo xcode-select -s /Applications/Xcode_10.1.app

    - name: Build the app
      run: xcodebuild -workspace OfflineGPSTracker_iOS.xcworkspace -scheme OfflineGPSTracker_iOS -sdk iphonesimulator -configuration Debug build -destination 'platform=iOS Simulator,name=iPhone 11,OS=12.1'

    - name: Run tests
      run: xcodebuild test -workspace OfflineGPSTracker_iOS.xcworkspace -scheme OfflineGPSTracker_iOS -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11,OS=12.1'

    - name: Archive the app
      run: xcodebuild -workspace OfflineGPSTracker_iOS.xcworkspace -scheme OfflineGPSTracker_iOS -sdk iphonesimulator -configuration Release archive -archivePath $PWD/build/OfflineGPSTracker_iOS.xcarchive
