name: iOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'

    - name: Install CocoaPods
      run: sudo gem install cocoapods

    - name: Install dependencies
      run: pod install --repo-update
      working-directory: ios

    - name: Set up Xcode
      run: sudo xcode-select -s /Applications/Xcode_12.5.app

    - name: Build the app
      run: xcodebuild -workspace ios/OfflineGPSTracker.xcworkspace -scheme OfflineGPSTracker -sdk iphonesimulator -configuration Debug build -destination 'platform=iOS Simulator,name=iPhone 11,OS=14.4'

    - name: Run tests
      run: xcodebuild test -workspace ios/OfflineGPSTracker.xcworkspace -scheme OfflineGPSTracker -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11,OS=14.4'

    - name: Archive the app
      run: xcodebuild -workspace ios/OfflineGPSTracker.xcworkspace -scheme OfflineGPSTracker -sdk iphonesimulator -configuration Release archive -archivePath $PWD/build/OfflineGPSTracker.xcarchive
